[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
default-src 'self';
script-src 'self' https://www.paypal.com https://www.paypalobjects.com 'unsafe-inline' 'unsafe-eval' blob:;
style-src 'self' 'unsafe-inline';
img-src 'self' data: https://www.paypalobjects.com https://www.paypal.com https://*.supabase.co;
frame-src https://www.paypal.com https://*.paypal.com blob:;
connect-src 'self' https://*.supabase.co wss://*.supabase.co https://www.paypal.com https://api.paypal.com;
font-src 'self';
"""
