[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self'
        https://www.paypal.com
        https://www.paypalobjects.com
        https://www.sandbox.paypal.com
        'unsafe-inline'
        'unsafe-eval'
        blob:;
      style-src 'self' 'unsafe-inline';
      img-src
        'self'
        data:
        blob:
        https:
        https://*.supabase.co
        https://www.paypalobjects.com;
      frame-src
        https://www.paypal.com
        https://www.sandbox.paypal.com
        blob:;
      connect-src
        'self'
        https://api.supabase.co
        https://*.supabase.co
        wss://*.supabase.co
        https://www.paypal.com
        https://api.paypal.com
        https://www.sandbox.paypal.com;
      font-src 'self' data:;
    """
